### ISSUE TITLE
AttributeError: module 'six.moves' has no attribute 'collections_abc'

### ISSUE THREAD

**Issue by TheBrage** [programmer2514/RPi-Google-Drive#1]
Hi,
When i try to use you script i get an error.

Traceback (most recent call last):
  File "/usr/local/bin/gdfs", line 76, in <module>
    _main()
  File "/usr/local/bin/gdfs", line 73, in _main
    option_string=option_string)
  File "/usr/local/lib/python3.7/dist-packages/gdrivefs/gdfuse.py", line 914, in mount
    gdrivefs.account_info.AccountInfo().get_data()
  File "/usr/local/lib/python3.7/dist-packages/gdrivefs/account_info.py", line 19, in get_data
    return gd.get_about_info()
  File "/usr/local/lib/python3.7/dist-packages/gdrivefs/drive.py", line 65, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gdrivefs/drive.py", line 199, in get_about_info
    client = self.__auth.get_client()
  File "/usr/local/lib/python3.7/dist-packages/gdrivefs/drive.py", line 161, in get_client
    discoveryServiceUrl=discoveryUrl)
  File "/usr/local/lib/python3.7/dist-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/googleapiclient/discovery.py", line 288, in build
    adc_key_path=adc_key_path,
  File "/usr/local/lib/python3.7/dist-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/googleapiclient/discovery.py", line 466, in build_from_document
    if isinstance(client_options, six.moves.collections_abc.Mapping):
AttributeError: module 'six.moves' has no attribute 'collections_abc'

Thanks

**Comment by programmer2514** [comment]
This is not an issue with my script, but an outdated python issue. Executing the following commands should fix it:
```
pip install google-api-python-client -U
pip install six -U
```
Hope this helps!

P.S. Sorry for the long response time - I somehow managed to lock myself out of my Github account 😄

**Comment by Techno11** [comment]
This did not fix the issue, I still get the same error. No files every sync into my google drive folder.

**Comment by programmer2514** [comment]
Try the same thing listed above, but replace `pip` with `pip3`. I am certain that this is a third party issue because my script is just a QOL installer for a command line tool. I will still attempt to fix the problem, but I most likely won't be able to if the above method does not work.

**Comment by programmer2514** [comment]
@Techno11 I updated the script and published a new release - try it out and tell me if it is fixed.
